--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: awesomestemwijzer
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: awesomestemwijzer
    spec: 
      containers: 
        - 
          image: rmeertens/partyrecommender
          name: inconfig
          volumeMounts:
            - 
              name: secrets
              mountPath: /etc/mysecrets
              readOnly: true
      volumes: 
        - 
          name: secrets
          secret: 
            secretName: mysslcertificate
--- 
apiVersion: v1
kind: Service
metadata:
  name: beschrijfwijzerexternal
spec:
  ports:
    - port: 443
      targetPort: 5009
      protocol: TCP
  selector:
    app: awesomestemwijzer
  clusterIP: 10.3.247.190
  type: LoadBalancer